version: "3.4"
services:
  packmate:
    container_name: packmate-app
    build:
      context: .
      dockerfile: Dockerfile_app
    network_mode: "host"
    image: packmate-app:v1
    depends_on:
      - db
    restart: always
  db:
    container_name: packmate-db
    build:
      context: .
      dockerfile: Dockerfile_db
    network_mode: "host"
    image: packmate-db:v1
    restart: always
