version: "3.4"
services:
  packmate:
    environment:
      DB_USER: ${PACKMATE_DB_USER:-BinaryBears}
      DB_PASSWORD: ${PACKMATE_DB_PASSWORD:-K604YnL3G1hp2RDkCZNjGpxbyNpNHTRb}
      DB_NAME: ${PACKMATE_DB_NAME:-packmate}
      INTERFACE: ${PACKMATE_INTERFACE}
      LOCAL_IP: ${PACKMATE_LOCAL_IP}
      WEB_LOGIN: ${PACKMATE_WEB_LOGIN:-BinaryBears}
      WEB_PASSWORD: ${PACKMATE_WEB_PASSWORD:-13371337}
    container_name: packmate-app
    build:
      context: .
      dockerfile: Dockerfile_app
    network_mode: "host"
    image: packmate-app:v1
    command: [
      "/usr/bin/java", "-Djava.net.preferIPv4Stack=true", "-Djava.net.preferIPv4Addresses=true",
      "-jar", "/app/app.jar", "--spring.datasource.url=jdbc:postgresql://127.0.0.1:65001/$${DB_NAME}",
      "--spring.datasource.username=$${DB_USER}", "--spring.datasource.password=$${DB_PASSWORD}",
      "--interface-name=$${INTERFACE}", "--local-ip=$${LOCAL_IP}", "--account-login=$${WEB_LOGIN}",
      "--account-password=$${WEB_PASSWORD}", "--server.port=65000", "--server.address=0.0.0.0"
    ]
    depends_on:
      - db
    restart: unless-stopped
  db:
    container_name: packmate-db
    build:
      context: .
      dockerfile: Dockerfile_db
      args:
        POSTGRES_USER: ${PACKMATE_DB_USER:-BinaryBears}
        POSTGRES_PASSWORD: ${PACKMATE_DB_PASSWORD:-K604YnL3G1hp2RDkCZNjGpxbyNpNHTRb}
        POSTGRES_DB: ${PACKMATE_DB_NAME:-packmate}
    network_mode: "host"
    image: packmate-db:v1
    restart: unless-stopped
