spring:
  datasource:
    url: "jdbc:postgresql://localhost/packmate"
    username: "packmate"
    password: "123456"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true


enable-capture: true
interface-name: enp0s31f6
local-ip: "192.168.0.125"
account-login: BinaryBears
account-password: 123456
udp-stream-timeout: 20 # секунд
tcp-stream-timeout: 40 # секунд
timeout-stream-check-interval: 10 # секунд
ignore-empty-packets: true
unpack-gzipped-http: true