spring:
  datasource:
    url: "jdbc:postgresql://localhost/packmate"
    username: "packmate"
    password: "123456"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update